### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by araujobsd**
Fix the issues related on https://github.com/iocage/iocage/issues/297

Also built it on FreeBSD: 1101001 and 1200030

### CODE REVIEW

**Comment by araujobsd** [comment]
Thank you!

**Comment by jceel** [comment]
Why did you close that PR before I merged it, @araujobsd?

**Comment by araujobsd** [comment]
I got confused, there is this repo and there is another one under FreeNAS!! I thought this one was not used anymore.

**Comment by jceel** [comment]
No, this is the main (upstream) repo. FreeNAS one is a fork.

**Pull request merged**
